### ISSUE TITLE
enh: Tests

### ISSUE THREAD

**Issue by nicl-nno** [aimclub/ProtoLLM#40]
From SDK:

![image](https://github.com/user-attachments/assets/84c6947f-3b35-46a8-9545-1895c2c86e2a)

**Comment by DRMPN** [comment]
Updated test summary for SDK tests can be found in #32. 

__Example:__

![image](https://github.com/user-attachments/assets/3ae8dfa3-3f30-4d86-b1b1-15f903b5a524)


https://github.com/aimclub/ProtoLLM/actions/runs/12460866875/job/34779661451
